### ISSUE TITLE
extensions do not seem to be registering

### ISSUE THREAD

**Issue by jcarpe** [devoptix/gulp-nunjucks-api#7]
I am trying to add a custom tag via extensions however I have not been successful both via requiring the .js file, nor by creating my function in an object. Both are illustrated below. I don't believe I should be having to call `addExtension()` as I believe `gulp-nunjucks-api` should be doing that for me, but is that incorrect?

```
'use strict';

const
	path 			= require( 'path' ),
	gulp 			= require( 'gulp' ),
	nunjucksRender 	= require( 'gulp-nunjucks-api' ),
	nunjucks 		= nunjucksRender.nunjucks,

	temp_pth		= './src/templates/'
	;

gulp.task( 'compile-templates', () => {

	return gulp.src( temp_pth+'pages/index.nunjucks' )
		.pipe( nunjucksRender({
			verbose: true,
			src: [ 
				path.join( __dirname, '..', temp_pth, 'pages' ),
				path.join( __dirname, '..', temp_pth, 'components' )
			],
			// extensions: require( path.join( __dirname, 'template-extensions/component.js' ) )
			extensions: {
				component: function() {

					this.tags = ['component'];

					this.parse = function(parser, nodes, lexer) {
						var token = parser.nextToken();

						var args = parser.parseSignature(null, true);
						parser.advanceAfterBlockEnd(token.value);

						return new nodes.CallExtension(this, 'run', args);
					};

					this.run = function(context, name, data) {
						return nunjucks.render('./src/templates/components/' + name + '.nunjucks', data);
					};

				}
			}
		}))
		.pipe( gulp.dest( path.join( GLOBAL.config.buildPath, 'site' ) ) )
		;
	
});
```
This is the error I get when trying to compile:
```
[11:47:09] Handling error: Template render error: (/Projects/proj/src/templates/pages/index.nunjucks) [Line 25, Column 5]
  unknown block tag: component

events.js:141
      throw er; // Unhandled 'error' event
      ^
Template render error: (/Projects/proj/src/templates/pages/index.nunjucks) [Line 25, Column 5]
  unknown block tag: component
    at Object.exports.prettifyError (/Projects/proj/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Projects/proj/node_modules/nunjucks/src/environment.js:468:27)
    at /Projects/proj/node_modules/nunjucks/src/environment.js:311:35
```

**Comment by waynebloss** [comment]
Take a look at the last line of the example code here - http://mozilla.github.io/nunjucks/api.html#custom-tags

It shows this:

```js
env.addExtension('RemoteExtension', new RemoteExtension());
```

gulp-nunjucks-api is looping over the property keys of the `opts.extensions` object basically calling that line above for you...but it's not doing `addExtension(new opts.extensions.component())` it's just doing `addExtension(opts.extensions.component)`.

So, in your code above - you should be setting your component field to an instance of the function, not the function...something like this:

```js
extensions: { component: new MyComponent(); }
```

Or I guess you could even do something like this:

```js
extensions: { component: new (function() { ... }) }
```

**Comment by waynebloss** [comment]
Basically component should be an object that has `parse`, `tags` and `run` functions, not a constructor function.

I will clarify that in the README sometime.

**Comment by jcarpe** [comment]
Ah ha, great thanks!
